# Generated by Django 5.1.1 on 2024-09-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("english", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groups",
            name="starting_time",
            field=models.DateTimeField(default="2024-12-31 00:00:00"),
        ),
    ]
