# Generated by Django 5.1.1 on 2024-09-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("english", "0002_groups_starting_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groups",
            name="starting_time",
            field=models.DateField(default="2024-12-31"),
        ),
    ]
