# Generated by Django 5.1.1 on 2024-09-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("english", "0003_alter_groups_starting_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groups",
            name="starting_time",
            field=models.DateField(),
        ),
    ]
