# Generated by Django 5.1.1 on 2024-09-23 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("english", "0004_alter_groups_starting_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name": "Teacher"},
        ),
    ]
