# Generated by Django 5.1.1 on 2024-09-24 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("english", "0006_alter_groups_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_teachers",
                to="english.lesson",
            ),
        ),
    ]
